/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119869-g3ac7d70291-20250611"
#endif /* AVUTIL_FFVERSION_H */
